[package]
name = "fsleu"
version = "0.1.0"
edition = "2021"
authors = ["KiwGucci<kiw.a.gucci@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globmatch= "0.2.1"
anyhow="1.0.66"
rustyline="10.0.0"
crossterm="0.25.0"